services:
  database:
    image: postgis/postgis:14-3.3
    ports:
      - "5400:5432"
    volumes:
      - ./data/database:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped

  pg_admin:
    image: dpage/pgadmin4:6.14
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./config/pg_admin:/var/lib/pgadmin
    env_file: .env
    restart: unless-stopped
    depends_on:
      - database

  webdav:
    image: drakkan/sftpgo:2.3.x-alpine-slim
    ports:
      - 2022:2022
      - "8080:8080"
      - "10080:10080"
    volumes:
      - ./data/webdav:/srv/sftpgo
    environment:
      - SFTPGO_WEBDAVD__BINDINGS__0__PORT=10080

  syncthing:
    image: syncthing/syncthing:1.23
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    volumes:
      - ./data/syncthing:/var/syncthing
    restart: unless-stopped